info:
  component: Hotel Details

eureka:
  instance:
#    hostname: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#      cluster: hyatt
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:7979/eureka/
      
server:
#  port: 9000
  port: 0
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    com.netflix: DEBUG

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
    
hystrix:
  stream:
    maxConcurrentConnections: 20
    bus:
      enabled: true
      
#spring:
#  boot:
#    admin:
#      url: http://localhost:8080